"""Create Tag and CompanyTag tables with relationships

Revision ID: f251cbb8f824
Revises: 2658c2e5aeca
Create Date: 2025-03-21 23:08:07.309740

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f251cbb8f824'
down_revision = '2658c2e5aeca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('problem_company_tags',
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('company_tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_tag_id'], ['company_tag.id'], ),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('problem_id', 'company_tag_id')
    )
    op.create_table('problem_tags',
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('problem_id', 'tag_id')
    )
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.drop_column('company_tags')
        batch_op.drop_column('tags')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('company_tags', mysql.TEXT(), nullable=True))

    op.drop_table('problem_tags')
    op.drop_table('problem_company_tags')
    op.drop_table('tag')
    op.drop_table('company_tag')
    # ### end Alembic commands ###
